import { writeFileSync } from 'node:fs';
import { analyzeWordAI } from '../lib/ai';
import { SEED_ENTRIES } from '../lib/wordAnalysisSeeds';
import { cacheKeyFor } from '../lib/wordAnalysisCache';
import type { CachedWordAnalysis } from '../lib/wordAnalysisCache';

const CONTEXT =
  'قُلْ أُوحِيَ إِلَيَّ أَنَّهُ اسْتَمَعَ نَفَرٌ مِّنَ الْجِنِّ فَقَالُوا إِنَّا سَمِعْنَا قُرْآنًا عَجَبًا يَهْدِي إِلَى الرُّشْدِ فَآمَنَّا بِهِ وَلَنْ نُشْرِكَ بِرَبِّنَا أَحَدًا';

const WORDS: { text: string; root?: string }[] = [
  { text: 'قُرْآنًا', root: 'قرا' },
];

const seeds: Record<string, CachedWordAnalysis> = { ...SEED_ENTRIES };
const ok: string[] = [];
const failed: string[] = [];

for (const w of WORDS) {
  const key = cacheKeyFor(w.text);
  console.log(`\n>>> analyzing «${w.text}» (root guess: ${w.root || '-'})`);
  try {
    const res = await analyzeWordAI({ wordText: w.text, root: w.root, context: CONTEXT, provider: 'openrouter' });
    if (!res.wordAnalysis || !res.wordAnalysis.root) {
      failed.push(w.text);
      console.log('    INVALID — no wordAnalysis (fallback to local analyzer)');
      continue;
    }
    const a = res.wordAnalysis;
    const quality =
      a.rootLetters?.length > 0 &&
      typeof a.simpleDefinition === 'string' &&
      a.simpleDefinition.length > 10 &&
      Array.isArray(a.lexiconReferences) &&
      a.lexiconReferences.length >= 1;
    if (!quality) {
      failed.push(w.text);
      console.log(`    THIN — refs:${a.lexiconReferences?.length} def:${a.simpleDefinition?.length}ch`);
      continue;
    }
    seeds[key] = {
      word: w.text,
      root: a.root,
      model: res.model,
      cachedAt: 4000000000000,
      analysis: a,
    };
    ok.push(w.text);
    console.log(`    OK root=${a.root} refs=${a.lexiconReferences.length} (${res.model})`);
  } catch (e: any) {
    failed.push(w.text);
    console.log('    ERROR:', e.message?.slice(0, 120));
  }
}

const out = `import type { CachedWordAnalysis } from './wordAnalysisCache';

/**
 * Curated analyses generated by the linguistic agent (real data, web-grounded).
 * Seeded into the cache so the first request for these words is instant.
 * Keys are diacritic-stripped clean text (same as cacheKeyFor output).
 */
export const SEED_ENTRIES: Record<string, CachedWordAnalysis> = ${JSON.stringify(seeds, null, 2)};
`;

writeFileSync('lib/wordAnalysisSeeds.ts', out, 'utf-8');
console.log(`\n==== wrote lib/wordAnalysisSeeds.ts (${Object.keys(seeds).length} seeds) ====`);
console.log('OK:', ok.join(', ') || '—');
console.log('FAILED:', failed.join(', ') || '—');
